#ifndef EBUSSETUPTOOLS_GLOBAL_H
#define EBUSSETUPTOOLS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EBUSSETUPTOOLS_LIBRARY)
#  define EBUSSETUPTOOLSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define EBUSSETUPTOOLSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EBUSSETUPTOOLS_GLOBAL_H
