#ifndef LIBXCONFPROTO_GLOBAL_H
#define LIBXCONFPROTO_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBXCONFPROTO_LIBRARY)
#  define LIBXCONFPROTOSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBXCONFPROTOSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBXCONFPROTO_GLOBAL_H
